config/routes.rb
InstrumentTracker::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
    
  resources :models, only: [:index, :show]
  resources :services, only: [:index, :show, :create, :update, :destroy]
  resources :statuses, only: [:index, :show]
  resources :facedeployments, controller: 'statuses', status_type: 'Facedeployment',  only: [:index, :edit, :show, :update, :destroy]
  resources :loans, controller: 'statuses', status_type: 'Loan',  only: [:index, :edit, :show, :update, :destroy]
  resources :losts, controller: 'statuses', status_type: 'Lost',  only: [:index, :edit, :show, :update, :destroy]  
  resources :storages, controller: 'statuses', status_type: 'Storage',  only: [:index, :edit, :show, :update, :destroy]
  resources :deployments, controller: 'statuses', status_type: 'Deployment',  only: [:index, :edit, :show, :update, :destroy]
  resources :retirements, controller: 'statuses', status_type: 'Retirement',  only: [:index, :edit, :show, :update, :destroy]
  
  resources :instruments do
    resources :services,  only: [:index, :new, :edit]
    resources :statuses,  only: [:index]
    resources :facedeployments, controller: 'statuses', status_type: 'Facedeployment',  only: [:index, :new, :create]  
    resources :storages, controller: 'statuses', status_type: 'Storage',  only: [:index, :new, :create]  
    resources :deployments, controller: 'statuses', status_type: 'Deployment',  only: [:index, :new, :create]  
    resources :loans, controller: 'statuses', status_type: 'Loan',  only: [:index, :new, :create]  
    resources :losts, controller: 'statuses', status_type: 'Lost',  only: [:index, :new, :create]  
    resources :retirements, controller: 'statuses', status_type: 'Retirement',  only: [:index, :new, :create]  
  end
  
  root  'static_pages#home'
  match '/about',       to: 'static_pages#about',   via: 'get'
  match '/help',       to: 'static_pages#help',   via: 'get'
  match '/contact',       to: 'static_pages#contact',   via: 'get'
  match '/dashboard',       to: 'static_pages#dashboard',   via: 'get'

  match '/deployments/site/:site_id', to: 'statuses#index', via: :get, :as => :deployments_site
  

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :instrument, :class_name => 'Instrument', :foreign_key => 'instrument_id'
  belongs_to :reporter, :class_name => 'User', :foreign_key => 'reporter_id'
  
  default_scope -> { order('created_at DESC') }
  
  validates :startdatetime, presence: true
  validates :problem, presence: true
  validates :instrument_id, presence:true
  validates :reporter_id, presence:true
  
  validate :validate_instrument_id
  validate :validate_reporter_id
  validate :start_before_end
  
  
  private 
    
  def validate_instrument_id
    errors.add(:instrument_id, "is invalid") unless Instrument.exists?(self.instrument_id)
  end
    
  def validate_reporter_id
    errors.add(:reporter_id, "is invalid") unless User.exists?(self.reporter_id)
  end    

  def start_before_end
    if !self.startdatetime.nil? && !self.startdatetime!="" && !self.enddatetime.nil? && !self.enddatetime!=""
      errors.add(:base, "End Date cannot precede Start Date") if self.startdatetime > self.enddatetime
    end
  end    
    
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :correct_user,  only: [:edit, :update, :destroy]
  
  load_and_authorize_resource :instrument
  load_and_authorize_resource :service, :through => :instrument, :shallow => true
  
  
  def index
   @services = Service.paginate(page: params[:page], :per_page => 20)
  end

  def new
    @instrument = Instrument.find(params[:instrument_id])
    @service = Service.new
  end

  def create
    @instrument = Instrument.find(service_params[:instrument_id])
    @service = @instrument.services.build(service_params)
    @service.reporter = current_user
    
    if @service.save
      flash[:success] = "Service record created!"
      redirect_to @service
    else
      @services = []
      @instrument = Instrument.find(service_params[:instrument_id])
      render 'services/new'
    end
  end

  def edit
    @service = Service.find(params[:id])
    @instrument = @service.instrument
  end

  def update
    @service = Service.find(params[:id])
    @instrument = @service.instrument
    if @service.update_attributes(service_params)
      flash[:success] = "Service updated"
      redirect_to @service
    else
      render 'edit'
    end
  end

  def show
    @service = Service.find(params[:id])
    @instrument = @service.instrument
  end

  def destroy
    @service.destroy
    redirect_to services_path
  end
   
  
  private

    def service_params
      params.require(:service).permit(:instrument_id, :problem, :startdatetime, :enddatetime, :comments, :reporter_id)
    end
    
    def correct_user
      @service = Service.find_by(id:params[:id])
      @inst_id = @service.instrument.id
      @instrument = current_user.instruments.find_by(id: @inst_id)
      redirect_to root_url if @instrument.nil?
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_services.html.erb
<% if @services.any? %>
  <h5 class="topspace20"><%= @services.count %> results</h5>
  <%= will_paginate @services, :param_name => "page" %>
  
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Service ID</th>
        <th>Instrument Serial Number</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Reported By</th>
        <th>View?</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'services/services_table', collection: @services, as: :service %>
    </tbody>
  </table>
  
<% else %>
  <p>No Servicing Records found</p>
<% end %>

app/views/services/_services_table.html.erb
<tr>
  <td><%= service.id %></td>
  <td><%= service.instrument.serialNumber %> </td>
  <td><%= service.startdatetime.strftime('%a %b %d %Y') %> </td>
  <td>
		<% if service.enddatetime %> 
  	  <%= service.enddatetime.strftime('%a %b %d %Y') %> 
  	<% end %>
  </td>
  <td><%= service.reporter.firstname %> <%= service.reporter.surname %> </td>
  <td><%= link_to "View", service %></td>
</tr>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/destroy.html.erb
<h1>Services#destroy</h1>
<p>Find me in app/views/services/destroy.html.erb</p>

app/views/services/edit.html.erb
<% provide(:title, 'Edit Service Record') %>
<% provide(:pageheading, 'Edit Service Record ' + @service.id.to_s + ' for Instrument '+ @instrument.id.to_s) %>

<%= form_for @service, :html => {:class => "form-horizontal"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <!-- Include hidden instrument element for attaching to correct instrument-->
  <%= f.hidden_field :instrument_id, :value => @instrument.id %>
   
  
  <div class="form-group">
    <%= f.label :startdatetime, 'Start Date', :class => "col-lg-2 control-label" %>
    <div class="col-lg-8"> 
      <%= f.date_field :startdatetime, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :enddatetime, 'End Date', :class => "col-lg-2 control-label" %>
    <div class="col-lg-8"> 
      <%= f.date_field :enddatetime, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :problem, "Description of Problem", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_area :problem, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :comments, "Comments", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_area :comments, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-4 col-md-offset-4 topspace50 bottomspace">
      <%= f.submit "Update", :class => "btn btn-large btn-primary" %>
    </div>
  </div>
  
<% end %>

<!-- <script type="text/javascript">
$('#projects, #facilities').multiselect({
    buttonClass : "form-control",
    buttonWidth: "50%",
    maxHeight: 400,
    enableFiltering: true
});
</script> -->

app/views/services/index.html.erb
<% provide(:title, 'Servicing List') %>
<% provide(:pageheading, 'Servicing List') %>

<div class="row">
  <div class="col-xs-12">
    <%= render 'services/services' %>
  </div>
</div>

app/views/services/new.html.erb
<% provide(:title, 'New Service Record') %>

<% provide(:pageheading, 'New Service Record for Instrument ' + @instrument.id.to_s) %>


<%= form_for @service, :html => {:class => "form-horizontal"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <!-- Include hidden instrument element for attaching to correct instrument-->
  <%= f.hidden_field :instrument_id, :value => @instrument.id %>
   
  
  <div class="form-group">
    <%= f.label :startdatetime, 'Start Date', :class => "col-lg-2 control-label" %>
    <div class="col-lg-8"> 
      <%= f.date_field :startdatetime, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :enddatetime, 'End Date', :class => "col-lg-2 control-label" %>
    <div class="col-lg-8"> 
      <%= f.date_field :enddatetime, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :problem, "Description of Problem", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_area :problem, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :comments, "Comments", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_area :comments, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-4 col-md-offset-4 topspace50 bottomspace">
      <%= f.submit "Submit", :class => "btn btn-large btn-primary" %>
    </div>
  </div>
  
<% end %>

<!-- <script type="text/javascript">
$('#projects, #facilities').multiselect({
    buttonClass : "form-control",
    buttonWidth: "50%",
    maxHeight: 400,
    enableFiltering: true
});
</script> -->

app/views/services/show.html.erb
<style type="text/css">
  table {
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
  }
  td {
    border-width: 0; 
    border-style: none;
    border-color: #0000ff; 
    border-collapse: collapse; 
    padding: 0; 
    margin: 0; 
    width: 10px; 
    height: 10px; 
  }
  td.black { background-color: #000; }
  td.white { background-color: #fff; }
</style>

<% provide(:title, 'Servicing Record View') %>
<% provide(:pageheading, 'Servicing Record '+ @service.id.to_s) %>

<!-- Add edit/delete buttons if current user -->
<% if @service.instrument.users.include? current_user %> 
 <div class="row bottomspace">  
    <div class="col-xs-12 col-sm-2 col-sm-push-10">
		<a class="btn btn-block btn-info" data-toggle="dropdown" href="#" id="options_button">
		  Options
		  <span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
		  <li><%= link_to "Edit Service", edit_instrument_service_path(instrument_id:@instrument.id, id:@service.id) %> </li>
		  <li><%= link_to "Delete Service", @service, :method => :delete, data: { confirm: "Are you sure?" }, :class=>"redtext" %></li>
	  </ul>
	</div>
  </div>
<% end %>


<div class="row">
	<div class="col-sm-12 well well-sm">	
		<p class='center'>This is a Service Record for the <span style="font-weight:bold"><%= @service.instrument.model.manufacturer.name %> <%= @service.instrument.model.name %></span> Instrument with Serial Number <span style="font-weight:bold"><%= @service.instrument.serialNumber %></span></p>	
		<p class='center text-muted'><%= link_to "View Instrument", @service.instrument %></p>		
	</div>
</div>


<div class="row topspace20">
  <div class="col-md-12">	
	
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Service ID</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @service.id %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Instrument Serial Number</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @service.instrument.serialNumber %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Problem description</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @service.problem %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Start Date/Time</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @service.startdatetime.strftime('%a %b %d %Y') %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">End Date/Time</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted">
		  	  <% if @service.enddatetime %> 
		  	    <%= @service.enddatetime.strftime('%a %b %d %Y') %>
		  	  <% end %>
		  	</p> 
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Comments</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @service.comments %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Reported by</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @service.reporter.firstname %> <%= @service.reporter.surname %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Record reported on</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @service.created_at.to_date.strftime('%a %b %d %Y') %></p>
		  </div>
		</div>
		
  </div>
  
</div>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>