config/routes.rb
InstrumentTracker::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
    
  resources :models, only: [:index, :show]
  resources :services, only: [:index, :show, :create, :update, :destroy]
  resources :statuses, only: [:index, :show]
  resources :facedeployments, controller: 'statuses', status_type: 'Facedeployment',  only: [:index, :edit, :show, :update, :destroy]
  resources :loans, controller: 'statuses', status_type: 'Loan',  only: [:index, :edit, :show, :update, :destroy]
  resources :losts, controller: 'statuses', status_type: 'Lost',  only: [:index, :edit, :show, :update, :destroy]  
  resources :storages, controller: 'statuses', status_type: 'Storage',  only: [:index, :edit, :show, :update, :destroy]
  resources :deployments, controller: 'statuses', status_type: 'Deployment',  only: [:index, :edit, :show, :update, :destroy]
  resources :retirements, controller: 'statuses', status_type: 'Retirement',  only: [:index, :edit, :show, :update, :destroy]
  
  resources :instruments do
    resources :services,  only: [:index, :new, :edit]
    resources :statuses,  only: [:index]
    resources :facedeployments, controller: 'statuses', status_type: 'Facedeployment',  only: [:index, :new, :create]  
    resources :storages, controller: 'statuses', status_type: 'Storage',  only: [:index, :new, :create]  
    resources :deployments, controller: 'statuses', status_type: 'Deployment',  only: [:index, :new, :create]  
    resources :loans, controller: 'statuses', status_type: 'Loan',  only: [:index, :new, :create]  
    resources :losts, controller: 'statuses', status_type: 'Lost',  only: [:index, :new, :create]  
    resources :retirements, controller: 'statuses', status_type: 'Retirement',  only: [:index, :new, :create]  
  end
  
  root  'static_pages#home'
  match '/about',       to: 'static_pages#about',   via: 'get'
  match '/help',       to: 'static_pages#help',   via: 'get'
  match '/contact',       to: 'static_pages#contact',   via: 'get'
  match '/dashboard',       to: 'static_pages#dashboard',   via: 'get'

  match '/deployments/site/:site_id', to: 'statuses#index', via: :get, :as => :deployments_site
  

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status_type
  before_action :set_status_type_text
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  load_and_authorize_resource :instrument
  load_and_authorize_resource :status, :through => :instrument, :shallow => true

  
  def index
    if params[:instrument_id]
      @statuses = status_type_class.where(instrument_id:params[:instrument_id])
      @instrument = Instrument.find(params[:instrument_id])
    elsif params[:site_id]
      #  return a list of only instruments from 'current' deployment at a particular site
      @instruments = Instrument.where(id: view_context.current_site_deployments(params[:site_id]).map(&:id))
    else
      # when not bounded by a particular instrument we return a list of only instruments from 'current' statuses
      @instruments = Instrument.where(id: view_context.current_instruments(status_type).map(&:id))
    end
  end

  def show
    @status = Status.find(params[:id])
    @instrument = @status.instrument
  end

  def new
    @instrument = Instrument.find(params[:instrument_id])
    @status = status_type_class.new
  end

  def edit
    @status = Status.find(params[:id])
  end


  def create
    @instrument = Instrument.find(status_params[:instrument_id])
    @status = @instrument.statuses.build(status_params)
    @status.reporter = current_user
    @status.status_type = @status_type
    
    if @status.save
      if @status.status_type == 'Retirement'
        flash[:success] = "Instrument has been retired!"
      else  
        flash[:success] = @status.status_type_text + " Record Created!"
      end
      @status = Status.find(@status.id)
      redirect_to @status
    else
      @statuses = []
      @instrument = Instrument.find(status_params[:instrument_id])
      @status_type = @status_type
      render 'new'
    end
  end
   
  def update
    @status = Status.find(params[:id])
    if @status.update_attributes(status_params)
      flash[:success] = @status.status_type_text + " Record Updated"
      redirect_to @status
    else
      render 'edit'
    end
  end


  def destroy
    @instrument = @status.instrument
    @status.destroy
    flash[:success] = @status.status_type_text + " Record Deleted!"
    redirect_to @instrument
  end
  
  
  private

    def set_status_type 
      @status_type = status_type 
    end
    
    def set_status_type_text 
      @status_type_text = status_type_text 
    end
    
    def status_type 
      Status.status_types.include?(params[:status_type]) ? params[:status_type] : "Status"
    end
    
    def status_type_text
      case status_type
      when 'Loan'
        'Loan'
      when 'Lost'
        'Lost'
      when 'Deployment'
        'Deployment'
      when 'Facedeployment'
        'FACE Deployment'
      when 'Storage'
        'In Storage'
      when 'Retirement'
        'Retired'
      else
        'Status'
      end
    end
    
    def status_type_class 
      status_type.constantize 
    end
    
    def status_params
      params.require(@status_type.downcase).permit(:instrument_id, :loaned_to, :startdate, :enddate, :address, :comments, :reporter_id, :status_type, :ring, :northing, :easting, :vertical, \
        :storage_location_id, :site_id, :location_identifier)
    end
    
    def correct_user
      @status = Status.find_by(id:params[:id])
      @inst_id = @status.instrument.id
      @instrument = current_user.instruments.find_by(id: @inst_id)
      redirect_to root_url if @instrument.nil?
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_statuses.html.erb
<% if @statuses.any? %>
  <h5 class="topspace20"><%= @statuses.count %> results</h5>
  
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Status ID</th>
        <th>Instrument Serial Number</th>
        <th>Status Type</th>
        <th>Start Date</th>
        <th>Reported By</th>
        <th>View?</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'statuses/statuses_table', collection: @statuses, as: :status %>
    </tbody>
  </table>
  
<% else %>
  <p>No Records found</p>
<% end %>

app/views/statuses/_statuses_table.html.erb
<tr>
  <td><%= status.id %></td>
  <td><%= status.instrument.serialNumber %> </td>
  <td><%= status.status_type_text %> </td>
  <td><%= status.startdate.strftime('%a %b %d %Y') %> </td>
  <td><%= status.reporter.firstname %> <%= status.reporter.surname %> </td>
  <td><%= link_to "View", status %></td>
</tr>

app/views/statuses/create.html.erb
<h1>Statuses#create</h1>
<p>Find me in app/views/statuses/create.html.erb</p>

app/views/statuses/destroy.html.erb
<h1>Statuses#destroy</h1>
<p>Find me in app/views/statuses/destroy.html.erb</p>

app/views/statuses/edit.html.erb
<% provide(:title, 'Edit '+ @status.status_type_text + ' Record') %>

<% provide(:pageheading, 'Edit '+ @status.status_type_text + ' Record ' + @status.id.to_s + ' for Instrument '+ @status.instrument.id.to_s) %>

<%= form_for @status, :html => {:class => "form-horizontal"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <!-- Include hidden instrument element for attaching to correct instrument-->
  <%= f.hidden_field :status_type, :value => @status_type %>
   
  
  <div class="form-group">
    <%= f.label :startdate, 'Start Date', :class => "col-lg-2 control-label" %>
    <div class="col-lg-8"> 
      <%= f.date_field :startdate, :class => "form-control" %>
    </div>
  </div>
  
  <% if @status.status_type == 'Storage' %> 
	  <div class="form-group">
		  <%= f.label :storage_location_id, 'Storage Location', :class => "col-lg-2 control-label" %>
		  <div class="col-lg-8">
		    <%= collection_select(:storage, :storage_location_id, StorageLocation.all, :id, :code, {include_blank: 'None selected', :selected => @status.storage_location_id.to_i}, {:class=>"form-control", :id=>'storage_locations'} ) %>
		  </div>
		</div>
	<% end %>

  <% if @status.status_type == 'Deployment' %> 
	  <div class="form-group">
		  <%= f.label :site_id, 'Site', :class => "col-lg-2 control-label" %>
		  <div class="col-lg-8">
		    <%= collection_select(:deployment, :site_id, Site.all, :id, :shortname, {include_blank: 'None selected', :selected => @status.site_id.to_i}, {:class=>"form-control", :id=>'sites'} ) %>
		  </div>
		</div>
	<% end %>
  
  <% if @status.status_type == 'Loan' %> 
	  <div class="form-group">
	    <%= f.label :enddate, 'End Date', :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8"> 
	      <%= f.date_field :enddate, :class => "form-control" %>
	    </div>
	  </div>
	  
	  <div class="form-group">
	    <%= f.label :address, "Loaned to", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.text_field :loaned_to, :class => "form-control" %>
	    </div>
	  </div>
	  
	  <div class="form-group">
	    <%= f.label :address, "Address of Loanee", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.text_area :address, :class => "form-control" %>
	    </div>
	  </div>
  <% end %>
	
  <% if @status.status_type == 'Facedeployment' %> 
	  <div class="form-group">
	    <%= f.label :ring, 'Ring', :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8"> 
	      <%= f.number_field :ring, :class => "form-control" %>
	    </div>
	  </div>
	  
	  <div class="form-group">
	    <%= f.label :northing, "Northing", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.number_field :northing, :class => "form-control", :step => 0.01 %>
	    </div>
	  </div>
	  	  
	  <div class="form-group">
	    <%= f.label :easting, "Easting", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.number_field :easting, :class => "form-control", :step => 0.01 %>
	    </div>
	  </div>
	  
	  <div class="form-group">
	    <%= f.label :vertical, "Vertical", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.number_field :vertical, :class => "form-control", :step => 'any' %>
	    </div>
	  </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :comments, "Comments", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_area :comments, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-4 col-md-offset-4 topspace50 bottomspace">
      <%= f.submit "Update", :class => "btn btn-large btn-primary" %>
    </div>
  </div>
  
<% end %>

app/views/statuses/index.html.erb
<% provide(:title, @status_type_text + ' List') %>

<% if @instrument %>

  <% provide(:pageheading, @status_type_text + ' List for Instrument '+@instrument.id.to_s) %>

  <div class="row">
	  <div class="col-xs-12">
	    <%= render 'statuses/statuses' %>
	  </div>
	</div>

<% else %>  <!-- In this case we will actually be exposing a list of instruments with the current status -->

  <% provide(:pageheading, @status_type_text + ' List') %>

	<div class="row">
	  <div class="col-xs-12">
	    <%= render 'instruments/instruments' %>
	  </div>
	</div>

<% end %>

app/views/statuses/new.html.erb
<% if @status.status_type == 'Retirement' %> 
  <% provide(:title, 'Instrument Retirement') %>
  <% provide(:pageheading, 'Retire Instrument '+ @instrument.id.to_s) %>
<% else %>
  <% provide(:title, 'New '+@status.status_type_text+' Record') %>
  <% provide(:pageheading, 'New '+ @status.status_type_text + ' Record for Instrument ' + @instrument.id.to_s) %>
<% end %>

<%= form_for [:instrument, @status], :html => {:class => "form-horizontal"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <!-- Include hidden instrument element for attaching to correct instrument-->
  <%= f.hidden_field :instrument_id, :value => @instrument.id %>
  <%= f.hidden_field :status_type, :value => @status_type %>
   
  
  <div class="form-group">
  	<% if @status.status_type == 'Retirement' %> 
      <%= f.label :startdate, 'Start Date of Retirement', :class => "col-lg-2 control-label" %>
    <% else %>  
      <%= f.label :startdate, 'Start Date', :class => "col-lg-2 control-label" %>
    <% end %>
    <div class="col-lg-8"> 
      <%= f.date_field :startdate, :class => "form-control" %>
    </div>
  </div>
  
  <% if @status.status_type == 'Loan' %> 
	  <div class="form-group">
	    <%= f.label :enddate, 'End Date', :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8"> 
	      <%= f.date_field :enddate, :class => "form-control" %>
	    </div>
	  </div>
	  
	  <div class="form-group">
	    <%= f.label :address, "Loaned to", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.text_field :loaned_to, :class => "form-control" %>
	    </div>
	  </div>
	  
	  <div class="form-group">
	    <%= f.label :address, "Address of Loanee", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.text_area :address, :class => "form-control" %>
	    </div>
	  </div>
  <% end %>
  
  <% if @status.status_type == 'Facedeployment' %> 
	  <div class="form-group">
	    <%= f.label :ring, 'Ring', :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8"> 
	      <%= f.number_field :ring, :class => "form-control" %>
	    </div>
	  </div>
	  
	  <div class="form-group">
	    <%= f.label :northing, "Northing", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.number_field :northing, :class => "form-control", :step => 0.01 %>
	    </div>
	  </div>
	  	  
	  <div class="form-group">
	    <%= f.label :easting, "Easting", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.number_field :easting, :class => "form-control", :step => 0.01 %>
	    </div>
	  </div>
	  
	  <div class="form-group">
	    <%= f.label :vertical, "Vertical", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.number_field :vertical, :class => "form-control", :step => 'any' %>
	    </div>
	  </div>
  <% end %>
  
  <% if @status.status_type == 'Storage' %> 
	  <div class="form-group">
		  <%= f.label :storage_location_id, 'Storage Location', :class => "col-lg-2 control-label" %>
		  <div class="col-lg-8">
		    <%= collection_select(:storage, :storage_location_id, StorageLocation.all, :id, :code, {include_blank: 'None selected'}, {:class=>"form-control", :id=>'storage_locations'} ) %>
		  </div>
		</div>
	<% end %>
  
  <% if @status.status_type == 'Deployment' %> 
	  <div class="form-group">
		  <%= f.label :site_id, 'Site', :class => "col-lg-2 control-label" %>
		  <div class="col-lg-8">
		    <%= collection_select(:deployment, :site_id, Site.all, :id, :shortname, {include_blank: 'None selected'}, {:class=>"form-control", :id=>'sites'} ) %>
		  </div>
		</div>
	  
	  <div class="form-group">
	    <%= f.label :northing, "Northing", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.number_field :northing, :class => "form-control", :step => 0.01 %>
	    </div>
	  </div>
	  	  
	  <div class="form-group">
	    <%= f.label :easting, "Easting", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.number_field :easting, :class => "form-control", :step => 0.01 %>
	    </div>
	  </div>
	  
	  <div class="form-group">
	    <%= f.label :vertical, "Vertical", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.number_field :vertical, :class => "form-control", :step => 'any' %>
	    </div>
	  </div>
	 
	  <div class="form-group">
	    <%= f.label :location_identifier, "Location Identifier", :class => "col-lg-2 control-label" %>
	    <div class="col-lg-8">
	      <%= f.text_field :location_identifier, :class => "form-control" %>
	    </div>
	  </div>
	<% end %>  
  
  <div class="form-group">
    <%= f.label :comments, "Comments", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_area :comments, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-4 col-md-offset-4 topspace50 bottomspace">
      <%= f.submit "Submit", :class => "btn btn-large btn-primary" %>
    </div>
  </div>
  
<% end %>

app/views/statuses/show.html.erb
<style type="text/css">
  table {
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
  }
  td {
    border-width: 0; 
    border-style: none;
    border-color: #0000ff; 
    border-collapse: collapse; 
    padding: 0; 
    margin: 0; 
    width: 10px; 
    height: 10px; 
  }
  td.black { background-color: #000; }
  td.white { background-color: #fff; }
</style>

<% provide(:title, @status.status_type_text + ' Record View') %>
<% provide(:pageheading, 'Instrument ' + @status.status_type_text + ' Record') %>

<!-- Add edit/delete buttons if current user -->
<% if can? :edit, @status %>
 <div class="row bottomspace">  
    <div class="col-xs-12 col-sm-2 col-sm-push-10">
		<a class="btn btn-block btn-info" data-toggle="dropdown" href="#" id="options_button">
		  Options
		  <span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
		  <% if @status.status_type == 'Loan'%>
		    <li><%= link_to 'Edit ' + @status.status_type_text + ' Record', edit_loan_path(id:@status.id) %> </li>
		  <% elsif @status.status_type == 'Lost'%>
		    <li><%= link_to 'Edit ' + @status.status_type_text + ' Record', edit_lost_path(id:@status.id) %> </li>
		  <% elsif @status.status_type == 'Facedeployment'%>
		    <li><%= link_to 'Edit ' + @status.status_type_text + ' Record', edit_facedeployment_path(id:@status.id) %> </li>
		  <% elsif @status.status_type == 'Storage'%>
		    <li><%= link_to 'Edit ' + @status.status_type_text + ' Record', edit_storage_path(id:@status.id) %> </li>
		  <% elsif @status.status_type == 'Storage'%>
		    <li><%= link_to 'Edit ' + @status.status_type_text + ' Record', edit_storage_path(id:@status.id) %> </li>
		  <% elsif @status.status_type == 'Deployment'%>
		    <li><%= link_to 'Edit ' + @status.status_type_text + ' Record', edit_deployment_path(id:@status.id) %> </li>
		  <% elsif @status.status_type == 'Retirement'%>
		    <li><%= link_to 'Edit ' + @status.status_type_text + ' Record', edit_deployment_path(id:@status.id) %> </li>
		  <% end %>
		  <li><%= link_to 'Delete '+ @status.status_type_text + ' Record', @status, :method => :delete, data: { confirm: "Are you sure?" }, :class=>"redtext" %></li>
	  </ul>
	</div>
  </div>
<% end %>


<div class="row">
	<div class="col-sm-12 well well-sm">	
		<p class='center'>This is a <%= @status.status_type.capitalize %> Record for the <span style="font-weight:bold"><%= @status.instrument.model.manufacturer.name %> <%= @status.instrument.model.name %></span> Instrument with Serial Number <span style="font-weight:bold"><%= @status.instrument.serialNumber %></span></p>	
		<p class='center text-muted'><%= link_to "View Instrument", @status.instrument %></p>		
	</div>
</div>


<div class="row topspace20">
  <div class="col-md-12">	
	
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Status ID</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @status.id %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Instrument Serial Number</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @status.instrument.serialNumber %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <% if @status.status_type == 'Retirement' %> 
		      <p class="text-left">Retired on</p>
		    <% elsif %>
		      <p class="text-left">Start Date</p>		
		    <% end %>    
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @status.startdate.strftime('%a %b %d %Y') %></p>
		  </div>
		</div>
		
		<% if @status.status_type == 'Loan' %> 
			<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Loaned to</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= @status.loaned_to %></p>
			  </div>
			</div>
	  <% end %>
	  
	  <% if @status.status_type == 'Facedeployment' %> 
			<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Ring</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= @status.ring %></p>
			  </div>
			</div>
			
			<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Northing</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= number_with_precision(@status.northing, :precision => 2) %></p>
			  </div>
			</div>
			
			<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Easting</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= number_with_precision(@status.easting, :precision => 2) %></p>
			  </div>
			</div>
			
			<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Vertical</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= number_with_precision(@status.vertical, :precision => 2) %></p>
			  </div>
			</div>
	  <% end %>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Comments</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @status.comments %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Reported by</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @status.reporter.firstname %> <%= @status.reporter.surname %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Record reported on</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @status.created_at.to_date.strftime('%a %b %d %Y') %></p>
		  </div>
		</div>
		
	  <% if @status.status_type == 'Deployment' %> 		
			<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Location Identifier</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= @status.location_identifier %></p>
			  </div>
			</div>	
			  
	  	<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Northing</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= number_with_precision(@status.northing, :precision => 2) %></p>
			  </div>
			</div>
			
			<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Easting</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= number_with_precision(@status.easting, :precision => 2) %></p>
			  </div>
			</div>
			
			<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Vertical</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= number_with_precision(@status.vertical, :precision => 2) %></p>
			  </div>
			</div>
			
	  <% end %> 	  
	  
	  <% if @status.status_type == 'Storage' %> 
	  <div class="row">
	    <div class="col-md-offset-3 col-md-6 well well-sm well-blue">	
			  <h4 class="center">Storage Location</h4>
				<div class="row topspace20">
				  <div class="col-md-6">
				    <p class="text-left">Storage Location code</p>
				  </div>   
				  <div class="col-md-6">
				    <p class="text-muted"><%= @status.storage_location.code %></p>
				  </div>
				  
				  <div class="col-md-6">
				    <p class="text-left">Room</p>
				  </div>   
				  <div class="col-md-6">
				    <p class="text-muted"><%= @status.storage_location.room %></p>
				  </div>
				  
				  <div class="col-md-6">
				    <p class="text-left">Building</p>
				  </div>   
				  <div class="col-md-6">
				    <p class="text-muted"><%= @status.storage_location.building %></p>
				  </div>
				  
				  <div class="col-md-6">
				    <p class="text-left">Address</p>
				  </div>   
				  <div class="col-md-6">
				    <p class="text-muted"><%= @status.storage_location.address %></p>
				  </div>
				  
				</div>
		  </div>
		</div>
	  <% end %>
	  
	  
	  <% if @status.status_type == 'Deployment' %> 
	  <div class="row">
	    <div class="col-md-offset-3 col-md-6 well well-sm well-blue">	
			  <h4 class="center">Site</h4>
				<div class="row topspace20">
				  <div class="col-md-6">
				    <p class="text-left">Site name</p>
				  </div>   
				  <div class="col-md-6">
				    <p class="text-muted"><%= @status.site.name %></p>
				  </div>
				  
				  <div class="col-md-6">
				    <p class="text-left">Address</p>
				  </div>   
				  <div class="col-md-6">
				    <p class="text-muted"><%= @status.site.address %></p>
				  </div>

				  <div class="col-md-6">
				    <p class="text-left">Site contact</p>
				  </div>   
				  <div class="col-md-6">
				    <p class="text-muted"><%= @status.site.contact %></p>
				  </div>
				  
				</div>
		  </div>
		</div>
	  <% end %>
		
  </div>
  
</div>

app/views/statuses/update.html.erb
<h1>Statuses#update</h1>
<p>Find me in app/views/statuses/update.html.erb</p>