config/routes.rb
InstrumentTracker::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
    
  resources :models, only: [:index, :show]
  resources :services, only: [:index, :show, :create, :update, :destroy]
  resources :statuses, only: [:index, :show]
  resources :facedeployments, controller: 'statuses', status_type: 'Facedeployment',  only: [:index, :edit, :show, :update, :destroy]
  resources :loans, controller: 'statuses', status_type: 'Loan',  only: [:index, :edit, :show, :update, :destroy]
  resources :losts, controller: 'statuses', status_type: 'Lost',  only: [:index, :edit, :show, :update, :destroy]  
  resources :storages, controller: 'statuses', status_type: 'Storage',  only: [:index, :edit, :show, :update, :destroy]
  resources :deployments, controller: 'statuses', status_type: 'Deployment',  only: [:index, :edit, :show, :update, :destroy]
  resources :retirements, controller: 'statuses', status_type: 'Retirement',  only: [:index, :edit, :show, :update, :destroy]
  
  resources :instruments do
    resources :services,  only: [:index, :new, :edit]
    resources :statuses,  only: [:index]
    resources :facedeployments, controller: 'statuses', status_type: 'Facedeployment',  only: [:index, :new, :create]  
    resources :storages, controller: 'statuses', status_type: 'Storage',  only: [:index, :new, :create]  
    resources :deployments, controller: 'statuses', status_type: 'Deployment',  only: [:index, :new, :create]  
    resources :loans, controller: 'statuses', status_type: 'Loan',  only: [:index, :new, :create]  
    resources :losts, controller: 'statuses', status_type: 'Lost',  only: [:index, :new, :create]  
    resources :retirements, controller: 'statuses', status_type: 'Retirement',  only: [:index, :new, :create]  
  end
  
  root  'static_pages#home'
  match '/about',       to: 'static_pages#about',   via: 'get'
  match '/help',       to: 'static_pages#help',   via: 'get'
  match '/contact',       to: 'static_pages#contact',   via: 'get'
  match '/dashboard',       to: 'static_pages#dashboard',   via: 'get'

  match '/deployments/site/:site_id', to: 'statuses#index', via: :get, :as => :deployments_site
  

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_many :instrument_users, :dependent => :destroy, inverse_of: :instrument
  has_many :users, :through => :instrument_users
  has_many :services, :class_name => 'Service', :foreign_key => 'instrument_id', :dependent => :destroy
  has_many :statuses, :class_name => 'Status', :foreign_key => 'instrument_id', :dependent => :destroy
  belongs_to :model, :class_name => 'Model', :foreign_key => 'model_id'
  
  accepts_nested_attributes_for :instrument_users
  
  default_scope -> { order('created_at DESC') }
  
  validates :serialNumber, :presence => { :message => "Serial Number is required" }
  validates :purchaseDate, :presence => { :message => "Purchase Date is required" }
  validates :model, :presence => { :message => "Model is required" }
  validates :model, :uniqueness => {:scope => [:serialNumber], message: "This Serial Number is already in use for an instrument of the same model"}
  
  # validate :require_at_least_one_user
 
  def current_status
    # Return the current status based on start dates
    if !self.statuses.empty?
      stat = Status.where(instrument_id:self.id).where('startdate <= ?', Date.today).order('startdate DESC').order('created_at DESC').first
    end
  end
  
  
  private

    def require_at_least_one_user
      if !self.id.nil?
        errors.add(:base, "An instrument must have at least one user associated with it") if
          self.users.count == 0 
      end
    end
    
end

app/models/instrument_type.rb
class InstrumentType < ActiveRecord::Base
  
  has_many :models, :class_name => 'Model', :foreign_key => 'instrument_type_id', :dependent => :restrict_with_exception
  
  # Order by name
  default_scope -> { order(name: :asc) }
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  load_and_authorize_resource
  
  def index   
    @instruments = Instrument.all   # Now using datatables for index table - no need for pagination
  end
  
  def new
    if Model.count == 0
      flash[:error] = "New Instruments can't be added until at least one Instrument Model is added to the system. Contact the admin to do this."
      redirect_to root_url
    else
      @instrument = Instrument.new
      @instrument.instrument_users.build
    end
  end

  def create
    @instrument = Instrument.create(instrument_params)
    if @instrument.save
      current_user.instruments << @instrument
      flash[:success] = "Instrument created!"
      redirect_to @instrument
    else
      @instruments = []
      render 'new'
    end
  end
  
  def show
    @instrument = Instrument.find(params[:id])
    @services = @instrument.services.paginate(page: params[:page], :per_page => 20)
    @statuses = @instrument.statuses.paginate(page: params[:page], :per_page => 20)
    @current_status = @instrument.current_status
  end
  
  def edit
    @instrument = Instrument.find(params[:id])
  end
     
  def update
    @instrument = Instrument.find(params[:id])
    if @instrument.update_attributes(instrument_params)
      current_user.instruments << @instrument
      flash[:success] = "Instrument updated"
      redirect_to @instrument
    else
      render 'edit'
    end
  end
  
  def destroy
    @instrument.destroy
    redirect_to instruments_path
  end
  
  
  private

    def instrument_params
      params.require(:instrument).permit(:model_id, :fundingSource, :assetNumber, :serialNumber, :supplier, :purchaseDate, :retirementDate, :price, :user_ids=> [])
    end
    
    def correct_user
      @instrument = current_user.instruments.find_by(id: params[:id])
      redirect_to root_url if @instrument.nil?
    end

  
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
  
  def current_instruments(statustype)
    # Will return an array of instruments whose current status_type is equal to statustype
    
    current_instruments = []
    Instrument.all.each do |i| 
      if !i.statuses.empty?
        if !i.current_status.nil? && i.current_status.status_type == statustype  # first clause is to weed out instrument that only have statuses in the future
          current_instruments << i
        end
      end
    end
    return current_instruments   
  end
  
  
  def current_site_deployments(site_id)
    # Will return an array of instruments which are currently deployed at a particluar site 
    
    current_site_deployments = []
    Instrument.all.each do |i| 
      if !i.statuses.empty?
        if !i.current_status.nil? && i.current_status.status_type == "Deployment"  # first clause is to weed out instrument that only have statuses in the future
          if i.current_status.site_id.to_s == site_id  # then filter down by particular site 
            current_site_deployments << i
          end
        end
      end
    end
    return current_site_deployments   
  end
  
  
  def unassigned_instruments
    unassigned = []
    Instrument.all.each do |i| 
      # First deal with instruments with no statuses assigned
      if i.statuses.empty?
        unassigned << i
      else
      #then for instruments with statuses only in the future
        if i.current_status.nil?
          unassigned << i
        end  
      end
    end
    return unassigned   
  end
  
  
end

app/views/instruments/_instruments.html.erb
<% if @instruments.any? %>
  <table class="table table-bordered table-striped table-hover" id="instruments">
    <thead>
      <tr>
        <th>Instrument ID</th>
        <th>Instrument Model</th>
        <th>Serial Number</th>
        <th>Asset Number</th>
        <th>Purchase Date</th>
        <th>Current Status</th>
        <th>View?</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'instruments/instruments_table', collection: @instruments, as: :instrument %>
    </tbody>
  </table>
  
<% else %>
  <p>No Instruments found</p>
<% end %>

app/views/instruments/_instruments_table.html.erb
<tr>
  <td><%= instrument.id %></td>
  <td><%= instrument.model.full_name %> </td>
  <td><%= instrument.serialNumber %> </td>
  <td><%= instrument.assetNumber %> </td>
  <td><%= instrument.purchaseDate.strftime('%a %b %d %Y') %></td>
  <% if !instrument.current_status.nil? %>
    <% if instrument.current_status.status_type_text == 'Deployment' %>
      <td><%= instrument.current_status.status_type_text + ' (' + instrument.current_status.site.shortname +  ')' %></td>
    <% else %>
      <td><%= instrument.current_status.status_type_text %></td>
    <% end %>

  <% else %>
    <td> None assigned </td>
  <% end %>
  <td><%= link_to "View", instrument %></td>
</tr>

app/views/instruments/edit.html.erb
<% provide(:title, 'Edit Instrument') %>
<% provide(:pageheading, 'Edit Instrument '+ @instrument.id.to_s) %>

<%= form_for @instrument, :html => {:class => "form-horizontal"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="form-group">
    <%= f.label :model_id, 'Model *', :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= collection_select(:instrument, :model_id, Model.all, :id, :full_name, {include_blank: 'None selected'}, {:class=>"form-control", :id=>'models'} ) %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :supplier, "Supplier", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_field :supplier, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :serialNumber, "Serial Number *", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_field :serialNumber, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :assetNumber, "Asset Number", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_field :assetNumber, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :purchaseDate, 'Purchase Date *', :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.date_field :purchaseDate, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :fundingSource, "Funding Source", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_field :fundingSource, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
	  <%= f.label :price, 'Price', :class => "col-lg-2 control-label"  %>
	  <div class="col-lg-8">
	    <%= f.number_field :price, :min => 0, :class => "form-control" %>  
	  </div> 
  </div> 
  
  <div class="form-group">
  	<%= f.label :user_ids, "Additional Owners", :class => "col-lg-2 control-label"  %>
    <div class="col-lg-8">
      <%= f.collection_select :user_ids, User.all.reject{|u| u == current_user}, :id, :fullname, {include_hidden:false}, { :class=>"form-control", :id=>'users', multiple:true } %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-4 col-md-offset-4 topspace50 bottomspace">
      <%= f.submit "Update", :class => "btn btn-large btn-primary" %>
    </div>
  </div>
  
<% end %>

<script type="text/javascript">
$('#users, #models').multiselect({
    includeSelectAllOption: true,
    buttonClass : "form-control",
    buttonWidth: "50%",
    maxHeight: 400,
    enableCaseInsensitiveFiltering: true,
    buttonWidth: '350px'
});
</script>

app/views/instruments/index.html.erb
<% provide(:title, 'Instrument List') %>
<% provide(:pageheading, 'Instrument List') %>

<div class="row">
  <div class="col-xs-12">
    <%= render 'instruments/instruments' %>
  </div>
</div>

app/views/instruments/new.html.erb
<% provide(:title, 'New Instrument') %>
<% provide(:pageheading, 'New Instrument') %>

<%= form_for @instrument, :html => {:class => "form-horizontal"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="form-group">
    <%= f.label :model_id, 'Model *', :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= collection_select(:instrument, :model_id, Model.all, :id, :full_name, {include_blank: 'None selected'}, {:class=>"form-control", :id=>'models'} ) %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :supplier, "Supplier", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_field :supplier, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :serialNumber, "Serial Number *", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_field :serialNumber, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :assetNumber, "Asset Number", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_field :assetNumber, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :purchaseDate, 'Purchase Date *', :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.date_field :purchaseDate, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :fundingSource, "Funding Source", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_field :fundingSource, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
	  <%= f.label :price, 'Price', :class => "col-lg-2 control-label"  %>
	  <div class="col-lg-8">
	    <%= f.number_field :price, :min => 0, :class => "form-control" %>  
	  </div> 
  </div> 

  <div class="form-group">
  	<%= f.label :user_ids, "Additional Owners", :class => "col-lg-2 control-label"  %>
    <div class="col-lg-8">
      <%= f.collection_select :user_ids, User.all.reject{|u| u == current_user}, :id, :fullname, {include_hidden:false}, { :class=>"form-control", :id=>'users', multiple:true } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 col-md-offset-4 topspace50 bottomspace">
      <%= f.submit "Submit", :class => "btn btn-large btn-primary" %>
    </div>
  </div>
  
<% end %>


<script type="text/javascript">
$('#users, #models').multiselect({
    includeSelectAllOption: true,
    buttonClass : "form-control",
    buttonWidth: "50%",
    maxHeight: 400,
    enableCaseInsensitiveFiltering: true,
    buttonWidth: '350px'
});
</script>

app/views/instruments/show.html.erb
<style type="text/css">
  table {
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
  }
  td {
    border-width: 0; 
    border-style: none;
    border-color: #0000ff; 
    border-collapse: collapse; 
    padding: 0; 
    margin: 0; 
    width: 10px; 
    height: 10px; 
  }
  td.black { background-color: #000; }
  td.white { background-color: #fff; }
</style>

<% provide(:title, 'Instrument View') %>
<% provide(:pageheading, 'Instrument '+ @instrument.id.to_s) %>

<!-- Add edit/delete buttons if current user -->

<% if can? :edit, @instrument %>
 <div class="row bottomspace">  
    <div class="col-xs-12 col-sm-2 col-sm-push-10">
		<a class="btn btn-block btn-info" data-toggle="dropdown" href="#" id="options_button">
		  Options
		  <span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
		    <li><%= link_to "Edit Instrument", :action => 'edit' %></li>
		    <li><%= link_to "Add Service Record", new_instrument_service_path(instrument_id:@instrument.id) %> </li>
		    <% if can? :destroy, @instrument %>
		      <li><%= link_to "Delete Instrument", @instrument, :method => :delete, data: { confirm: "Are you sure?" }, :class=>"redtext" %></li>
		    <% end %>
		    <li role="presentation" class="divider"></li>
		    <li role="presentation" class="dropdown-header">Add New Status</li>
		    <li><%= link_to "Instrument Loan", new_instrument_loan_path(instrument_id:@instrument.id) %> </li>
		    <li><%= link_to "Instrument Lost", new_instrument_lost_path(instrument_id:@instrument.id) %> </li>
		    <li><%= link_to "Instrument Storage", new_instrument_storage_path(instrument_id:@instrument.id) %> </li>
		    <li><%= link_to "FACE Deployment", new_instrument_facedeployment_path(instrument_id:@instrument.id) %> </li>
		    <li><%= link_to "Deployment", new_instrument_deployment_path(instrument_id:@instrument.id) %> </li>
			  <li role="presentation" class="divider"></li>
		    <li><%= link_to "Retire this instrument", new_instrument_retirement_path(instrument_id:@instrument.id) %> </li>
	    </ul>
	</div>
  </div>
<% end %>


<div class="row">
  <div class="col-md-7">	
	
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Instrument</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @instrument.id %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Serial Number</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @instrument.serialNumber %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Asset Number</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @instrument.assetNumber %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Supplier</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @instrument.supplier %></p>
		  </div>
		</div>
		
		
    <% if user_signed_in? %> 
			<div class="row">
			  <div class="col-md-offset-3 col-md-3">
			    <p class="text-left">Price</p>
			  </div>   
			  <div class="col-md-6">
			    <p class="text-muted"><%= @instrument.price %></p>
			  </div>
			</div>
    <% end %>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Purchase Date</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @instrument.purchaseDate.strftime('%a %b %d %Y') %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-offset-3 col-md-3">
		    <p class="text-left">Funding Source</p>
		  </div>   
		  <div class="col-md-6">
		    <p class="text-muted"><%= @instrument.fundingSource %></p>
		  </div>
		</div>
  </div>
  
  <div class="col-md-4 well">	
  	<h4 class="center">Model</h4>
  	
  	<div class="row topspace20">
		  <div class="col-md-5">
		    <p class="text-left">Instrument Type</p>
		  </div>   
		  <div class="col-md-7">
		    <p class="text-left text-muted"><%= @instrument.model.instrument_type.name %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-5">
		    <p class="text-left">Manufacturer</p>
		  </div>   
		  <div class="col-md-7">
		    <p class="text-left text-muted"><%= @instrument.model.manufacturer.name %></p>
		  </div>
		</div>
		
		<div class="row">
		  <div class="col-md-5">
		    <p class="text-left">Name</p>
		  </div>   
		  <div class="col-md-7">
		    <p class="text-left text-muted"><%= @instrument.model.name %></p>
		  </div>
		</div>
		
  </div>
  
</div>

<div class="row topspace20">
  <div class="col-md-offset-3 col-md-7 well well-blue">
  	<% if !@current_status.nil? %>
  	  <% if @current_status.status_type_text == 'Deployment' %>
        <h4 class="center">Current Status: <%= @current_status.status_type_text + ' (' + @current_status.site.shortname +  ')' %></td>
      <% else %>
	      <h4 class="center">Current Status: <%= @current_status.status_type_text %></h4>
	    <% end %>
	    <h5 class="center"><%= link_to "View Details", @current_status %></h5>
	  <% else %>
	    <h4 class="center">Current Status: None assigned</h4>
	  <% end %>
    
  </div>
</div>


<div class="row">
  <div class="col-xs-12 rowline">
    <h4>Contacts for this Instrument</h4>
    <% @instrument.users.each do |contact| %>
      <p><%= contact.firstname+' '+contact.surname+' ('+contact.email+')' %></p>
    <% end %>
  </div>
</div>


<div class="row">
  <div class="col-xs-12 rowline">
    <h4>Status History for this Instrument</h4>
    <%= render 'statuses/statuses' %>
  </div>
</div>


<div class="row">
  <div class="col-xs-12 rowline">
    <h4>Service History for this Instrument</h4>
    <%= render 'services/services' %>
  </div>
</div>