config/routes.rb
InstrumentTracker::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
    
  resources :models, only: [:index, :show]
  resources :services, only: [:index, :show, :create, :update, :destroy]
  resources :statuses, only: [:index, :show]
  resources :facedeployments, controller: 'statuses', status_type: 'Facedeployment',  only: [:index, :edit, :show, :update, :destroy]
  resources :loans, controller: 'statuses', status_type: 'Loan',  only: [:index, :edit, :show, :update, :destroy]
  resources :losts, controller: 'statuses', status_type: 'Lost',  only: [:index, :edit, :show, :update, :destroy]  
  resources :storages, controller: 'statuses', status_type: 'Storage',  only: [:index, :edit, :show, :update, :destroy]
  resources :deployments, controller: 'statuses', status_type: 'Deployment',  only: [:index, :edit, :show, :update, :destroy]
  resources :retirements, controller: 'statuses', status_type: 'Retirement',  only: [:index, :edit, :show, :update, :destroy]
  
  resources :instruments do
    resources :services,  only: [:index, :new, :edit]
    resources :statuses,  only: [:index]
    resources :facedeployments, controller: 'statuses', status_type: 'Facedeployment',  only: [:index, :new, :create]  
    resources :storages, controller: 'statuses', status_type: 'Storage',  only: [:index, :new, :create]  
    resources :deployments, controller: 'statuses', status_type: 'Deployment',  only: [:index, :new, :create]  
    resources :loans, controller: 'statuses', status_type: 'Loan',  only: [:index, :new, :create]  
    resources :losts, controller: 'statuses', status_type: 'Lost',  only: [:index, :new, :create]  
    resources :retirements, controller: 'statuses', status_type: 'Retirement',  only: [:index, :new, :create]  
  end
  
  root  'static_pages#home'
  match '/about',       to: 'static_pages#about',   via: 'get'
  match '/help',       to: 'static_pages#help',   via: 'get'
  match '/contact',       to: 'static_pages#contact',   via: 'get'
  match '/dashboard',       to: 'static_pages#dashboard',   via: 'get'

  match '/deployments/site/:site_id', to: 'statuses#index', via: :get, :as => :deployments_site
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <%= link_to "HIE Instrument Tracker", root_path, class: "navbar-brand"  %>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Help", help_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Sign out, "+current_user.firstname.capitalize, destroy_user_session_path, method: "delete" %></li>
	    <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
    
</nav>

app/views/layouts/_minibar.html.erb
<nav class="navbar navbar-default" id="minibar">
  <div class="container-fluid">
      <%= render 'layouts/minibar_links' %>
  </div>
</nav>

app/views/layouts/_minibar_links.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to "Dashboard", dashboard_path, :id => 'dashboard_link' %></li>
  
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Instruments<b class="caret"></b></a>
    <ul class="dropdown-menu">
    	
    	<% if can? :create, Instrument %>
	      <li>
	        <%= link_to 'Create New', new_instrument_path, :id => 'instruments_new' %>
	      </li>
        <li role="presentation" class="divider"></li>
      <% end %> 
		  <li role="presentation" class="dropdown-header">View Options</li>
      <li>
        <%= link_to 'All', instruments_path, :id => 'instruments_index' %>
      </li>
      <li>
        <%= link_to 'On Loan', loans_path, :id => 'loans_index' %>
      </li>
      <li>
        <%= link_to 'Lost', losts_path, :id => 'losts_index' %>
      </li>
      <li>
        <%= link_to 'In Storage', storages_path, :id => 'storages_index' %>
      </li>
      <li>
        <%= link_to 'Retired', retirements_path, :id => 'retirements_index' %>
      </li>
      <li>
        <%= link_to 'Deployed at FACE', facedeployments_path, :id => 'facedeployments_index' %>
      </li>

    	<li class="menu-item dropdown dropdown-submenu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Deployed</a>
        <ul class="dropdown-menu">
          <li class="menu-item ">
            <%= link_to 'All Deployed', deployments_path, :id => 'deployments_index' %>
          </li>
          <li role="presentation" class="divider"></li>
          
          <% Site.all.each do |site| %>
	          <li>
	            <%= link_to site.shortname, deployments_site_path(:site_id => site.id) %>
	          </li>
          <% end %>
        
        </ul>
      </li>     
      
    </ul>
  </li>
  
</ul>

<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle pull-right" data-toggle="dropdown">View Resources<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to 'Models', models_path, :id => 'models_index' %>
      </li>
    </ul>
  </li>
</ul>	

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Instrument tracker at Hawkesbury Institute for the Environment" />
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">      
      
      <%= render 'layouts/minibar' %>
      <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
		      <% flash.each do |key, value| %>
		        <div class="center alert alert-<%= key %>">
		          <%= value %>
		        </div>
		      <% end %>
        </div>
      </div>
		
      <h2 class="bottomspace"><%= yield(:pageheading) %></h2>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>